### ISSUE TITLE
Contacts+ hangs after importing contacts

### ISSUE THREAD

**Issue by ThomasDaheim** [libasys/contactsplus#100]
Hi,

I have migrated my Outlook contacts (~150) to contacts+. No error messages in the process, entries can be found in the database and can be synced from Thunderbird as well. So that seems to be OK.
When I try to view the contacts in ownCloud I see the following behavior:
- When starting Contacts+ my address book is shown with "0" entries in the left toolbar and in the main panel "No cards found!" - but only after some time of thinking (>10 secs)
- When clicking on the address book in the left toolbar the "busy" image appears and keeps rotating forever

I can see the following error in the log (not sure if related but timestamps match):

<code>
Exception: {"Exception":"Sabre\VObject\EofException","Message":"End of document reached prematurely","Code":0,"Trace":"#0 \/volume1\/web\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(133): Sabre\VObject\Parser\MimeDir->readLine()\n#1 \/volume1\/web\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(63): Sabre\VObject\Parser\MimeDir->parseDocument()\n#2 \/volume1\/web\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Reader.php(44): Sabre\VObject\Parser\MimeDir->parse('BEGIN:VCARD\r\nVE...', 0)\n#3 \/volume1\/web\/owncloud\/apps\/contactsplus\/lib\/app.php(889): Sabre\VObject\Reader::read('BEGIN:VCARD\r\nVE...')\n#4 \/volume1\/web\/owncloud\/apps\/contactsplus\/controller\/contactscontroller.php(1027): OCA\ContactsPlus\App::renderOutput(4, 'all')\n#5 [internal function]: OCA\ContactsPlus\Controller\ContactsController->getContactCards()\n#6 \/volume1\/web\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#7 \/volume1\/web\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\ContactsPlus\Controller\ContactsController), 'getContactCards')\n#8 \/volume1\/web\/owncloud\/lib\/private\/appframework\/app.php(108): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\ContactsPlus\Controller\ContactsController), 'getContactCards')\n#9 \/volume1\/web\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\AppFramework\App::main('ContactsControl...', 'getContactCards', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)\n#10 [internal function]: OC\AppFramework\routing\RouteActionHandler->__invoke(Array)\n#11 \/volume1\/web\/owncloud\/lib\/private\/route\/router.php(274): call_user_func(Object(OC\AppFramework\routing\RouteActionHandler), Array)\n#12 \/volume1\/web\/owncloud\/lib\/base.php(873): OC\Route\Router->match('\/apps\/contactsp...')\n#13 \/volume1\/web\/owncloud\/index.php(40): OC::handleRequest()\n#14 {main}","File":"\/volume1\/web\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php","Line":250} 
</code>

Any idea how to fix this?

Thanks,
Thomas
##

**Comment by ThomasDaheim** [comment]
Anyone?
