### ISSUE TITLE
Getting error messages after owncloud update to 8.1.3

### ISSUE THREAD

**Issue by sonst-was** [libasys/contactsplus#101]
Hi there,

I've just updated my owncloud installation to 8.1.3. After re-enabling Contacts+ I get a lot of error messages in the owncloud log:

```
{"reqId":"VgGquE@FNRwAAHRS26UAAAA5","remoteAddr":"##place-holder##","app":"OCP\\Share","message":"Sharing backend \\OCA\\CalendarPlus\\Share\\Backend\\Event not registered, \\OCA\\CalendarPlus\\Share\\Backend\\Event is already registered for calplevent","level":2,"time":"2015-09-22T19:23:37+00:00"} {"reqId":"VgGqvE@FNRwAAHRS26cAAAA5","remoteAddr":"##place-holder##","app":"OCP\\Share","message":"Sharing backend OCA\\ContactsPlus\\Share\\Backend\\Addressbook not registered, OCA\\ContactsPlus\\Share\\Backend\\Addressbook is already registered for cpladdrbook","level":2,"time":"2015-09-22T19:23:40+00:00"}
 {"reqId":"VgGqvE@FNRwAAHRS26cAAAA5","remoteAddr":"##place-holder##","app":"OCP\\Share","message":"Sharing backend OCA\\ContactsPlus\\Share\\Backend\\Contact not registered, OCA\\ContactsPlus\\Share\\Backend\\Contact is already registered for cplcontact","level":2,"time":"2015-09-22T19:23:40+00:00"} {"reqId":"VgGqvE@FNRwAAHRS26kAAAA5","remoteAddr":"##place-holder##","app":"OCP\\Share","message":"Sharing backend \\OCA\\TasksPlus\\Share\\Backend\\Vtodo not registered, \\OCA\\TasksPlus\\Share\\Backend\\Vtodo is already registered for calpltodo","level":2,"time":"2015-09-22T19:23:41+00:00"}
 {"reqId":"VgGq50@FNRwAAHPlOowAAAAD","remoteAddr":"##place-holder##","app":"PHP","message":"Missing argument 2 for OC\\Files\\Storage\\Wrapper\\Wrapper::file_put_contents(), called in \/var\/www\/web123\/html\/domain.de\/owncloud\/lib\/private\/files\/view.php on line 1006 and defined at \/var\/www\/web123\/html\/domain.de\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php#241","level":3,"time":"2015-09-22T19:24:23+00:00"}
 {"reqId":"VgGq50@FNRwAAHPlOowAAAAD","remoteAddr":"##place-holder##","app":"PHP","message":"Undefined variable: data at \/var\/www\/web123\/html\/domain.de\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php#242","level":3,"time":"2015-09-22T19:24:23+00:00"}
 {"reqId":"VgGq50@FNRwAAHPlOowAAAAD","remoteAddr":"##place-holder##","app":"index","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"OCA\\\\ContactsPlus\\\\Http\\\\ImageResponse::setImage The image resource is not valid.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/apps\\\/contactsplus\\\/http\\\/imageresponse.php(25): OCA\\\\ContactsPlus\\\\Http\\\\ImageResponse->setImage(Object(OCP\\\\Image))\\n#1 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/apps\\\/contactsplus\\\/controller\\\/contactscontroller.php(687): OCA\\\\ContactsPlus\\\\Http\\\\ImageResponse->__construct(Object(OCP\\\\Image))\\n#2 [internal function]: OCA\\\\ContactsPlus\\\\Controller\\\\ContactsController->getContactPhoto('68')\\n#3 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\ContactsPlus\\\\Controller\\\\ContactsController), 'getContactPhoto')\\n#5 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\ContactsPlus\\\\Controller\\\\ContactsController), 'getContactPhoto')\\n#6 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ContactsControl...', 'getContactPhoto', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/lib\\\/base.php(874): OC\\\\Route\\\\Router->match('\\\/apps\\\/contactsp...')\\n#10 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/apps\\\/contactsplus\\\/http\\\/imageresponse.php\",\"Line\":34}","level":4,"time":"2015-09-22T19:24:23+00:00"} {"reqId":"VgGq50@FNRwAAHPULIkAAAAS","remoteAddr":"##place-holder##","app":"PHP","message":"Missing argument 2 for OC\\Files\\Storage\\Wrapper\\Wrapper::file_put_contents(), called in \/var\/www\/web123\/html\/domain.de\/owncloud\/lib\/private\/files\/view.php on line 1006 and defined at \/var\/www\/web123\/html\/domain.de\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php#241","level":3,"time":"2015-09-22T19:24:24+00:00"}
 {"reqId":"VgGq50@FNRwAAHPULIkAAAAS","remoteAddr":"##place-holder##","app":"PHP","message":"Undefined variable: data at \/var\/www\/web123\/html\/domain.de\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php#242","level":3,"time":"2015-09-22T19:24:24+00:00"}
 {"reqId":"VgGq50@FNRwAAHPULIkAAAAS","remoteAddr":"##place-holder##","app":"index","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"OCA\\\\ContactsPlus\\\\Http\\\\ImageResponse::setImage The image resource is not valid.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/apps\\\/contactsplus\\\/http\\\/imageresponse.php(25): OCA\\\\ContactsPlus\\\\Http\\\\ImageResponse->setImage(Object(OCP\\\\Image))\\n#1 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/apps\\\/contactsplus\\\/controller\\\/contactscontroller.php(687): OCA\\\\ContactsPlus\\\\Http\\\\ImageResponse->__construct(Object(OCP\\\\Image))\\n#2 [internal function]: OCA\\\\ContactsPlus\\\\Controller\\\\ContactsController->getContactPhoto('136')\\n#3 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\ContactsPlus\\\\Controller\\\\ContactsController), 'getContactPhoto')\\n#5 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\ContactsPlus\\\\Controller\\\\ContactsController), 'getContactPhoto')\\n#6 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ContactsControl...', 'getContactPhoto', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/lib\\\/base.php(874): OC\\\\Route\\\\Router->match('\\\/apps\\\/contactsp...')\\n#10 \\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/web123\\\/html\\\/domain.de\\\/owncloud\\\/apps\\\/contactsplus\\\/http\\\/imageresponse.php\",\"Line\":34}","level":4,"time":"2015-09-22T19:24:24+00:00"}
```

But to be honest, I dont know whether they where there before the update too or not (according to the timestamps, at least those above are from after the update).
##

**Comment by doits** [comment]
+1
